# Generated by Django 6.0.1 on 2026-04-24 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'Everyone (Staff & Residents)'), ('RESIDENT', 'Residents Only'), ('STAFF', 'Staff Only')], default='ALL', max_length=20),
        ),
    ]
