# Generated by Django 5.2 on 2026-08-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_announcement_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
