# Generated by Django 6.0.1 on 2026-06-03 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartment', '0005_community_maintenance_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunitySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('TRIAL', 'Trial Period'), ('MONTHLY', 'Monthly Subscription'), ('YEARLY', 'Yearly Subscription')], default='TRIAL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Paid'), ('PENDING', 'Payment Pending'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('total_amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('next_billing_date', models.DateField()),
                ('community', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='apartment.community')),
            ],
        ),
    ]
