# Generated by Django 6.0.1 on 2026-06-03 12:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSaaSRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=490.0, max_digits=10)),
                ('yearly_rate', models.DecimalField(decimal_places=2, default=5999.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='communitysubscription',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='communitysubscription',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active / Subscribed'), ('EXPIRED', 'Expired / Deactivated')], default='ACTIVE', max_length=20),
        ),
    ]
