# Generated by Django 6.0.1 on 2026-06-03 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_community_maintenance_fee'),
        ('webapp', '0002_globalsaasrate_communitysubscription_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaaSPaymentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='SUCCESS', max_length=20)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.community')),
            ],
        ),
    ]
