# Generated by Django 5.2 on 2026-09-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_communitysubscription_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalsaasrate',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='globalsaasrate',
            name='yearly_rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
