# Generated by Django 6.0.1 on 2026-04-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bill',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payer',
        ),
        migrations.DeleteModel(
            name='SalaryPayment',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
