# Generated by Django 6.0.1 on 2026-06-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_support',
            field=models.BooleanField(default=False),
        ),
    ]
