# Generated by Django 6.0.1 on 2026-04-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0002_remove_communityhall_image_hallimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallbooking',
            name='attendees',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hallbooking',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
