# Generated by Django 6.0.1 on 2026-08-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_hallbooking_attendees_hallbooking_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallbooking',
            name='ac_room',
            field=models.BooleanField(default=False),
        ),
    ]
