# Generated by Django 6.0.1 on 2026-08-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0004_hallbooking_ac_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallbooking',
            name='ac_room',
            field=models.CharField(choices=[('AC', 'ac'), ('NON-AC', 'non-ac')], default='AC', max_length=10),
        ),
        migrations.AlterField(
            model_name='hallbooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], max_length=20),
        ),
    ]
