# Generated by Django 6.0.1 on 2026-08-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0005_alter_hallbooking_ac_room_alter_hallbooking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallbooking',
            name='ac_room',
            field=models.CharField(choices=[('AC', 'ac'), ('NON-AC', 'non-ac')], default='AC', max_length=20),
        ),
    ]
