# Generated by Django 6.0.1 on 2026-08-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0006_alter_hallbooking_ac_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallbooking',
            name='status',
            field=models.CharField(choices=[('AC', 'ac'), ('NON-AC', 'non-ac')], max_length=20),
        ),
    ]
