# Generated by Django 6.0.1 on 2026-08-25 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0008_remove_hallbooking_ac_room_communityhall_ac_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityhall',
            name='ac_room',
            field=models.CharField(choices=[('AC', 'ac'), ('NON_AC', 'non_ac')], default='AC', max_length=20),
        ),
    ]
