# Generated by Django 6.0.1 on 2026-08-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0009_alter_communityhall_ac_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityhall',
            name='ac_room',
            field=models.CharField(choices=[('AC', 'true'), ('NON_AC', 'false')], default='AC', max_length=20),
        ),
    ]
