# Generated by Django 6.0.1 on 2026-08-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0011_alter_communityhall_ac_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityhall',
            name='ac_room',
            field=models.CharField(choices=[('AC', True), ('NON_AC', False)], default='AC', max_length=20),
        ),
    ]
