# Generated by Django 6.0.1 on 2026-02-12 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='occupied',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
