# Generated by Django 6.0.1 on 2026-03-11 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_alter_community_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='occupied',
            field=models.BooleanField(default=False),
        ),
    ]
