# Generated by Django 6.0.1 on 2026-02-16 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0002_flat_occupied'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='admin',
            field=models.OneToOneField(default=20, limit_choices_to={'role': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_community', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
