# Generated by Django 6.0.1 on 2026-03-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_alter_flat_occupied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='flat',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddConstraint(
            model_name='block',
            constraint=models.UniqueConstraint(fields=('name', 'community'), name='unique_block_per_community'),
        ),
        migrations.AddConstraint(
            model_name='flat',
            constraint=models.UniqueConstraint(fields=('name', 'block'), name='unique_flat_per_block'),
        ),
    ]
