# Generated by Django 6.0.1 on 2026-04-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_alter_block_name_alter_flat_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='maintenance_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
