# Generated by Django 6.0.1 on 2026-04-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('RECEIVED', 'Received')], default='PENDING', max_length=20),
        ),
    ]
