# Generated by Django 6.0.1 on 2026-04-23 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall', '0003_hallbooking_attendees_hallbooking_is_paid_and_more'),
        ('salary', '0002_alter_salarypayment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='hall_booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='hall.hallbooking'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(choices=[('BILL_PAYMENT', 'Bill Payment'), ('SALARY_PAYMENT', 'Salary Payment'), ('HALL_BOOKING', 'Hall Booking')], max_length=20),
        ),
    ]
