# Generated by Django 5.2 on 2026-08-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_transaction_hall_booking_alter_transaction_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
