# Generated by Django 6.0.1 on 2026-08-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminresident_profile',
            name='paid_amount',
            field=models.CharField(blank=True, null=True),
        ),
    ]
