# Generated by Django 6.0.1 on 2026-02-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminresident_profile',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminresident_profile',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
