# Generated by Django 6.0.1 on 2026-02-09 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_staffprofile'),
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminresident_profile',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.block'),
        ),
        migrations.AlterField(
            model_name='adminresident_profile',
            name='flat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apartment.flat'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=50),
        ),
    ]
