# Generated by Django 6.0.1 on 2026-03-06 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_community'),
        ('apartment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='apartment.community'),
        ),
    ]
