# Generated by Django 6.0.1 on 2026-02-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_staffprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('RESIDENT', 'Resident'), ('STAFF', 'Staff')], max_length=25),
        ),
    ]
