# Generated by Django 6.0.1 on 2026-07-09 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_community'),
        ('apartment', '0005_community_maintenance_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='apartment.community'),
        ),
    ]
